### ISSUE TITLE
♻️ [Refactor] v2 page 병합

### ISSUE THREAD

**Issue by besyia0k0** [42connected/polar-fe#367]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 현재 진행중이었던 v2의 페이지를 현재의 리포지토리에 가져옵니다.

## 📝 리팩토링 상세 내용

- v1 페이지와 v2 페이지를 폴더로 구분하여, 기존 코드가 잘 실행되면서 추후에 진행될 리팩토링도 원만하게 진행될 수 있도록 합니다.

## ✅ TODO

- [ ] 파일 옮겨온 뒤, 새롭게 바뀐 style, component 올바르게 적용
