### ISSUE TITLE
✨[Feature] Ver2.0 Styles 폴더를 polar-fe레포에 합치기

### ISSUE THREAD

**Issue by Joo-hyun-Kang** [42connected/polar-fe#368]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

Ver2.0에 있는 스타일 폴더를 Ver1.0레포로 합칠 예정

## 📝 기능 상세 내용

합쳐서 기존 1.0 코드가 제대로 돌아가고 2.0코드도 제대로 돌아가게 할 거임
그리고 나서 1.0코드를 2.0으로 수정하면서 현재 푸시하는 스타일을 사용하게 될 거임

## ✅ TODO

- [ ] v1.0과 v2.0 글로벌 스타일 비교
- [ ] theme v1.0 v2.0으로 나누기
