### ISSUE TITLE
♻️ [Refactor] component 2.0 가져오기

### ISSUE THREAD

**Issue by kjy00** [42connected/polar-fe#369]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- component2.0 가져오기

## 📝 리팩토링 상세 내용

- polar-fe-v2의 common에 있는 컴포넌트들을 가져옵니다 !

## ✅ TODO

- [ ] polar-fe-v2의 component 가져오기

## 📍 레퍼런스

polar-fe-v2를 참고 .. !
