### ISSUE TITLE
✨[Feature] craco 적용하기

### ISSUE THREAD

**Issue by besyia0k0** [42connected/polar-fe#370]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- import할 시, 절대경로를 사용할 수 있도록 하는 craco 설치 및 적용

## 📝 기능 상세 내용

- v1, v2 폴더를 새로 생성하면서 각 페이지마다 상대경로로 import하다 보니 경로 이슈가 생김
- 이를 해결하기 위해 craco 설치 및 적용을 하려고 함.

## ✅ TODO

- [x] craco 설치 및 설정
- [x] 현재 페이지 및 컴포넌트 등에 변경사항 적용

## 📍 레퍼런스

v2 레포 참고 예정
