### ISSUE TITLE
✨[Feature] React-query

### ISSUE THREAD

**Issue by Seojunhwan** [42connected/polar-fe#372]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- https://github.com/42connected/polar-fe-v2/issues/49#issue-1447436529
상기 이슈와 같습니다.

## 📝 기능 상세 내용

- 리액트 쿼리로 서버 데이터 관리

## ✅ TODO

- [x] 만들어둔 React-query 코드 이전해야합니다.
- [x] 만들어둔 API 코드 이전해야합니다.
