### ISSUE TITLE
✨[Feature] Recoil

### ISSUE THREAD

**Issue by Seojunhwan** [42connected/polar-fe#373]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- https://github.com/42connected/polar-fe-v2/issues/50#issue-1447437701
상기 이슈와 같습니다.

## 📝 기능 상세 내용

- 전역 상태 관리를 위한 Recoil 적용

## ✅ TODO

- [x] 기존에 작성한 Recoil 관련 코드 이전

## 📍 레퍼런스

> [Docs](https://recoiljs.org/ko/)
