### ISSUE TITLE
 🚨 [Bug] 보고서 페이지 버그 수정

### ISSUE THREAD

**Issue by dkjefilsjl** [42connected/polar-fe#375]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 버그 개요

- 보고서 페이지 글씨 튀어나옴

## 📝 버그 상세 내용

- 보고서 페이지 글씨 튀어나오는 것 없도록 세팅

## ✅ TODO

- [x] 보고서 밀리는 이슈 수정
- [x] 이미지 넘어가는 이슈 수정
- [x] 보고서 내용이 칸 밖으로 튀어나오는 이슈 수정
