### ISSUE TITLE
✨[Feature] 멘토 마이페이지 중 멘토 정보에서 이미지 첨부에 대한 알림 추가하기

### ISSUE THREAD

**Issue by Joo-hyun-Kang** [42connected/polar-fe#377]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## 📄 기능 개요

멘토 마이페이지 중 멘토 정보에서 이미지 첨부에 대한 가이드 추가하기
웹에 올려있는 URL로 된 이미지는 첨부 가능하나 멘토님들 로컬에 있는 URL은 첨부가 안됌

## 📝 기능 상세 내용

멘토 정보 부분에 간단하게 알림 문구 추가

## ✅ TODO

- [ ] 멘토 정보 부분에 간단하게 알림 문구 추가

## 📍 레퍼런스

https://polar-bne7366.slack.com/archives/C0492BL7P2M/p1667812974080489
