### ISSUE TITLE
✨[Feature] React18

### ISSUE THREAD

**Issue by Seojunhwan** [42connected/polar-fe#378]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- React 18 적용

## 📝 기능 상세 내용

- `Suspense` 적용은 현재 버전인 `17` 에서도 가능합니다만 점진적으로 개선하기 위해 `18` 버전으로 업그레이드 추진 (당당!)
- `17` 에서 `18` 로 업그레이드 했을 때의 사이드 이펙트가 있는지 확인해야합니다.

## ✅ TODO

- [ ] `my-table` 컴포넌트에서 사용하는 라이브러리 관련 버전 이슈 확인 필요합니다.
- [ ] `Suspense` 적용
