### ISSUE TITLE
🚨 [Bug] reports 페이지 최대 줄바꿈 개수 조절

### ISSUE THREAD

**Issue by dkjefilsjl** [42connected/polar-fe#385]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

- reports 페이지에 줄 바꿈 제한이 없어, 보고서 출력 페이지에서 해당 칸을 벗어나는 경우가 발생했습니다.

## 🐞 버그 상세 내용

- report-detail 페이지에서 보고서 내용이 많은 엔터로 벗어나는 이슈가 있었습니다.

## ✅ TODO

- [ ] 보고서 내용 입력을 받을 때 줄 바꿈 개수 제한을 두기
