### ISSUE TITLE
♻️ [Refactor] API 분리

### ISSUE THREAD

**Issue by Seojunhwan** [42connected/polar-fe#386]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- API 콜 함수로 분리

## 📝 리팩토링 상세 내용

- `MobX` 에 다닥다닥 붙어있는 API 콜을 함수로 분리하여 재사용성을 높힙시다.

## ✅ TODO

- [ ] `MobX` 에서 API 콜 코드 함수로 분리
- [ ] **사이드 이펙트 확인**
- [ ] `API Response Intreface` 작성 필요
