### ISSUE TITLE
♻️ [Refactor] 저작권 이슈로 로고변경하기

### ISSUE THREAD

**Issue by Joo-hyun-Kang** [42connected/polar-fe#387]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

프리픽스에서 저작권을 사서 로고를 쓰고 있었으나 만료가 되어 변경 필요

## 📝 리팩토링 상세 내용

기존 로고를 대체해서 로고 공모전에서 받은 로고를 사용
폴라라는 글씨체는 남겨두었음(차후 개선 가능!)

## ✅ TODO

- [ ] main에 로고 이미지 바꾸기
- [ ] develop에도 로고 이미지 바꾸기
- [ ] 깃 허브에도 로고 바꾸기

**Comment by Seojunhwan** [comment]
@Joo-hyun-Kang 님!! 혹시 요거 `main` 브랜치에서 핫픽스로 변경하시는 거 어떠세요?

현재 `develop` 부터 올라가면 금요일에 작업한 사항까지 함께 배포될 것 같은데 현재 `develop` 은 어떤 사이드 이펙트가 있는지 불분명합니다 ㅠㅠ
