### ISSUE TITLE
♻️ [Refactor] 홈페이지 favicon 아이콘 변경 및  배포 스크립트 추가

### ISSUE THREAD

**Issue by jeounpar** [42connected/polar-fe#393]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 홈페이지 favicon 아이콘 변경 및 package.json에 배포 스크립트 추가

## 📝 리팩토링 상세 내용

- 기존 favicon 아이콘을 새로운 로고 아이콘으로 변경
- package.json에 배포 스크립트 추가 (임시)

## ✅ TODO

- [ ] 깃헙 액션을 이용한 CI/CD는 아직..

## 📍 레퍼런스
- none

**Comment by Seojunhwan** [comment]
@jeounpar FE CI/CD 도움 필요하시면 말씀해 주세요!

**Comment by jeounpar** [comment]
흑흑 감사합니다
